perfact/zodbsync

- config.py
- perfact/zodbsync/logger.py
- perfact/zodbsync/zodbsync.py
I improved user handling for empty databases. Also it helps thatlogging goes to console automatically if there is one.
> Improvements to logging and user handling

- perfact/zodbsync/helpers.py
Trying to really stabilize this difficult thing by being able to stack a bunch of doctests on `str_repr()` until no further problems can be found.
Tests are run thus:
python2 -m doctest -v helpers.py
python3 -m doctest -v helpers.py
> WIP: Modifications I'd make to this branch

- perfact/zodbsync/watcher.py
- perfact/zodbsync/zodbsync.py
> Consequently use relative paths and os.path.join

- CHANGELOG
- setup.py
They don't allow SSH access from here, so I'm trying to release a new version through the web interface...
> Release 3.12.5

- CHANGELOG
- perfact/zodbsync/commands/pick.py
- perfact/zodbsync/commands/record.py
- perfact/zodbsync/zodbsync.py
- setup.py
> Several small fixes and additions

- perfact/zodbsync/zodbsync.py
only to append the missing newline, only append it for files that were changed anyhow.
> Do not force re-recording of metadata

- .gitignore
- CHANGELOG
- README.md
- perfact/zodbsync/commands/pick.py
- perfact/zodbsync/commands/upload.py
- perfact/zodbsync/main.py
- perfact/zodbsync/subcommand.py
- perfact/zodbsync/tests/environment.py
- perfact/zodbsync/tests/test_sync.py
Started by writing boilder plate code
> zodbsync-upload

- perfact/zodbsync/commands/with_lock.py
I'm afraid I forgot to add the new file with the last PR...
> Actually supply the method for with-lock

- CHANGELOG
- perfact/zodbsync/commands/watch.py
> Unregister signals before waiting

- CHANGELOG
- perfact/zodbsync/commands/record.py
- perfact/zodbsync/helpers.py
- perfact/zodbsync/object_types.py
- perfact/zodbsync/tests/test_helpers.py
- perfact/zodbsync/tests/test_sync.py
Fixes #49
Fixes #50
Also fixes Generic Commit mails, which are broken since 4.0.2
> Several fixes

- CHANGELOG
- config.py
- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/commands/with_lock.py
- perfact/zodbsync/helpers.py
- perfact/zodbsync/subcommand.py
- perfact/zodbsync/tests/environment.py
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
- setup.py
Addresses #53.
Still needs to be tested, in particular with Zope2 without WSGI and with the watcher (but it should now be possible to write tests for the watcher!)
> Use explicit transaction manager

- CHANGELOG
- bin/perfact-zoperecord
- bin/zodbsync
- perfact/zodbsync/commands/pick.py
- perfact/zodbsync/commands/playback.py
- perfact/zodbsync/commands/record.py
- perfact/zodbsync/commands/upload.py
- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/commands/with_lock.py
- perfact/zodbsync/helpers.py
- perfact/zodbsync/main.py
- perfact/zodbsync/object_mixins.py
- perfact/zodbsync/object_types.py
- perfact/zodbsync/subcommand.py
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
- setup.py
Several larger refactoring steps, dependent on previous PRs.
> Refactoring

- CHANGELOG
- bin/perfact-zoperecord
- perfact/zodbsync/commands/pick.py
- perfact/zodbsync/commands/playback.py
- perfact/zodbsync/commands/record.py
- perfact/zodbsync/commands/reset.py
- perfact/zodbsync/commands/upload.py
- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/commands/with_lock.py
- perfact/zodbsync/main.py
Fixes #65  and #67. Shows docstring of each subcommand when calling with `--help`
> Some small fixes

- CHANGELOG
- tox.ini
> Make Python 2 tests work on Ubuntu

- CHANGELOG
- README.md
- perfact/zodbsync/commands/do.py
- perfact/zodbsync/commands/execute.py
- perfact/zodbsync/commands/pick.py
- perfact/zodbsync/commands/reset.py
- perfact/zodbsync/helpers.py
- perfact/zodbsync/main.py
- perfact/zodbsync/subcommand.py
- perfact/zodbsync/tests/test_sync.py
- setup.py
This is a generic subcommand that simplifies several git operations that
are automatically coupled with a playback.
Implements #70 
Existing tests run, but I need to actually test the functionality as well as the simplified versions of other commands.
> Add new subcommand "exec"

- CHANGELOG
- perfact/zodbsync/commands/upload.py
- perfact/zodbsync/subcommand.py
- perfact/zodbsync/tests/test_sync.py
- setup.py
This is a first working version which I used to push QA related SVGs, ODTs and PDFs into a system.
> Upload more filetypes

- CHANGELOG
- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/helpers.py
- perfact/zodbsync/tests/test_sync.py
Initialization is now done in a separately spawned subprocess
> Reduce memory footprint of watcher

- perfact/zodbsync/tests/test_sync.py
This testcases are the result of our university project for the Softwarequality module at FH Bielefeld. (cc: @batschko)
The added testcases represent some use case workflows that can be done with the application.
Lets us know if there are changes needed.
> Added several systemtest testcases

- CHANGELOG
- perfact/zodbsync/object_mixins.py
- perfact/zodbsync/tests/test_sync.py
There is an issue where the change of a property type is not correctly played back as `manage_changeProperties` does not allow changing of these. These properties need to be deleted and added with the new type!
> Implement changing of property types on playback

- CHANGELOG
- perfact/zodbsync/helpers.py
- perfact/zodbsync/subcommand.py
- perfact/zodbsync/tests/test_helpers.py
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
Also, add a minor cosmetic change and a new test
> Ensure rollback of failed pick for too many changed files

- CHANGELOG
- perfact/zodbsync/helpers.py
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
Aims to close #104. Currently, I only implemented a test demonstrating the problem.
> Allow replacing property by child

- CHANGELOG
- perfact/zodbsync/commands/pick.py
I've grown tired of having to work around this with `$(git log...)` so I figured I'd give us some arguments for that.
Happy holidays =P
> Add `since` and `until` arguments to the `pick` command
