- perfact/zodbsync/object_types.py
With this, reading and storing of permissions does no longer depend on the acquisition context, which is important for watch mode
> Change reading and storing of permissions

- perfact/zodbsync/helpers.py
I had trouble running `perfact-zoperecord` in a python3 environment, caused by some js libraries in the lib folder of my Data.fs.
Error was:
```bash
perfact-zoperecord -c zodbsync_config.py 
Traceback (most recent call last):
File ".../bin/perfact-zoperecord", line 129, in <module>
sync.record()
File ".../lib/python3.5/site-packages/perfact/zodbsync/zodbsync.py", line 618, in record
self.record_obj(obj, path, recurse=recurse)
File ".../lib/python3.5/site-packages/perfact/zodbsync/zodbsync.py", line 652, in record_obj
self.record_obj(obj=child, path=path+'/'+item)
File ".../lib/python3.5/site-packages/perfact/zodbsync/zodbsync.py", line 652, in record_obj
self.record_obj(obj=child, path=path+'/'+item)
File ".../lib/python3.5/site-packages/perfact/zodbsync/zodbsync.py", line 623, in …
```
> Fix python3 crash in read_pdata

- perfact/zodbsync/object_types.py
- perfact/zodbsync/zodbsync.py
`mod_write` created a copy `d` of `data` to make sure it was using a dict instead of a list of tuples. If no owner was defined in the filesystem data, the default owner was inserted into `d`, but `data` was passed to the corresponding handler.
> In playback, set owner to default owner if it not given on the FS

- CHANGELOG
- perfact/zodbsync/__init__.py
- perfact/zodbsync/commands/pick.py
- perfact/zodbsync/object_types.py
- setup.py
In addition, this finally `pep8`s `object_types.py` and fixes two issues that were overlooked in the refactoring for 3.14.0.dev0, namely a missing inclusion of the submodule `perfact.zodbsync.commands` and calls to `git` not being wrapped correctly.
I guess it is high time to think about how to wrap this module in tests.
> Allow commit ranges to be picked

- .gitignore
- CHANGELOG
- README.md
- conftest.py
- perfact/zodbsync/tests/environment.py
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
- setup.py
- tox.ini
This creates an environment for developing further tests, including a fixture that provides a full-fledged environment (running ZEO in a temporary directory, repository and configuration files) that can be used by tests.
Two tests are included, which can be run by starting the `tox` command in the checked out folder.
> Test setup

- CHANGELOG
- perfact/zodbsync/extedit.py
- setup.py
If the external editor is invoked with a path that leads to an object
not in its container but in an acquired context, saving changes to the
object could have the effect of creating a copy of the object instead.
For example, if a script called 'myscript' is located in / but accessed
with a path of /myfolder/myscript, Saving changes would create a
modified copy in /myfolder.
> Fix lookup of parent in external editor

- perfact/zodbsync/zodbsync.py
This fixes a bug introduced in #35 where new objects could no longer be
recorded because the comparison of old and new metadata was done after
stripping both of whitespaces without considering that one might be
`None`.
> Do not break when recording new objects

- CHANGELOG
- setup.py
When Zope 5 had not been released yet, the tests failed if the version was not pinned, but that seems to be fixed now.
> Allow installation under Zope 5

- CHANGELOG
- README.md
- config.py
- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/helpers.py
- perfact/zodbsync/main.py
- perfact/zodbsync/object_types.py
- perfact/zodbsync/subcommand.py
- perfact/zodbsync/zodbsync.py
This allows wrapping a series of shell commands in the file lock.
Additionally, some code cleanup was performed in the Python 2
compatibility wrappers, using `six` where this is applicable and using
current implementations of some helper functions that are also present
in `python-perfact`.
> Add subcommand `with-lock`

- README.md
Config path in README does not match the one given in `subcommand.py`.
> Default configuration path adjustment

- CHANGELOG
- perfact/zodbsync/tests/environment.py
- perfact/zodbsync/tests/test_sync.py
- setup.py
Tests that spawn a ZEO process now use a socket to communicate with it
instead of hoping that the hardcoded port is not used anywhere else. In
particular, if a test run fails abnormally and fails to clean up, there
might still be a spawned process left running, but it will not confuse
following test runs.
> Switch tests to use a socket for the ZEO connection

- CHANGELOG
- perfact/zodbsync/commands/watch.py
I'm afraid something else was broken with the 4.0.2 release. The signal handler for graceful shutdown of the watcher used `exit`, but since it was moved to a separate function, `exit` was not the `Signal` object that it was supposed to be.
> Restore graceful shutdown of watcher

- CHANGELOG
- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/object_types.py
- perfact/zodbsync/tests/test_sync.py
The fix for #22 in 4.0.3 wrongly assumed that get_local_roles() returns
a list of (user, role) pairs. Instead, it returns a list of (user,
roles) pairs, where the second element is a tuple of roles. This wrote
broken content into the object when playing it back.
> Fix playback of local_roles

- perfact/zodbsync/zodbsync.py
Found on a customer system using zope2, zodbsync stopped working with following error:
```
$ zodbsync watch
Error: positional arguments are not supported
For help, use /usr/share/perfact/zope2.13/bin/zodbsync -h
```
This PR should fix this error by clearing sys arguments before calling `configure_zope`
> Clear sys arguments before calling configure_zope in zope2

- perfact/zodbsync/zodbsync.py
Do not use import as version check ( which might be wrong at all ), also remember to import `sys` when using it ( which i forgot the first time, tox remembered me ).
> Always clear sys arguments before calling configure_zope regardless of the zope version

- CHANGELOG
- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/tests/test_sync.py
- setup.py
Since I could not find a way to get the current transaction ID after
starting a transaction, lastTransaction() should be read before the
transaction is started. This ensures that we do not read an old state
and miss important changes in all further updates because we already
assumed we were reading the state at the transaction stored in
`self.last_visible_transaction`.
Fixes #73.
> T211837: Fix timing issues in watcher

- CHANGELOG
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
Since we added `/acl_users` to the `.gitignore` file, I repeatedly accidentally played back a freshly cloned repository that was missing this top-level User Folder, deleting it. `zodbsync` was unable to recreate it, assuming it exists beforehand.
This PR changes the initialization so it creates this top-level User Folder if it is missing and `create_manager_user` is set in the config.
> Allow recreating the top-level User Folder if it is accidentally deleted

- perfact/zodbsync/subcommand.py
During bootcamp we encountered a nasty behaviour: One person calling a `pick` with conflicts, `git diff` output is piped into pager, keeping zodbsync lock! Second person gets `Unable to acquire lock.` . Simple solution is this PR, stopping git from piping to pager via `-P` option.
> Avoid piping git output to pager

- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/tests/test_sync.py
This PR aims to resolve #60 by correctly shutting down the watcher in case the filesystem does not match the currently stored tree! This PR also adds a Test-Case to validate that the correct Exception is thrown in the described use case!
> Restart on filesystem diff

- CHANGELOG
- perfact/zodbsync/commands/record.py
Add support to add a whitelist-separated list of email addresses to the codechange_email.
> Multiple recipients in codechange mail

- perfact/zodbsync/object_types.py
If these options are missing, we record database connectors incompletely.
> Add missing options use_tpc and datetime_str

- .github/workflows/check.yml
- tox.ini
Adds a github-workflow to execute the tox-tests on PRs and pushes to "master". This currently excludes all tests performed for python 2.7 as this is no longer supported by the official github-actions and we would require a custom action to as implemented [here](https://github.com/LizardByte/.github/blob/nightly/actions/setup_python2/action.yml). 
Due to there possibly being breaking changes in the codebase of Zope or ZEO which may result in the tests failing (as it was actually the case with ZEO 5.4, but fixed in 5.4.1) we could also consider setting these tests up to also be executed on a schedule!
To see this in action you can take a look at the dummy-PR created on my [personal fork](https://github.com/Wiseqube/zodbsync/pull/1)
> Add github-workflow to execute tox

- CHANGELOG
- bin/perfact-zopeplayback
- bin/zodbsync
- perfact/zodbsync/scripts.py
- setup.py
- tox.ini
`zc.buildout >=3` seems to ignore the `scripts` option in `setup.py`, so I refactored it into a entry-points which works successfully.
> Refactor scripts into entry points to be usable with zc.buildout >= 3.

- tox.ini
It got removed in https://github.com/perfact/zodbsync/pull/115
> Remove no longer existing bin dir from coverage config.

- .toxfiles/reqs-py2.txt
- CHANGELOG
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
During the serialization of forms from `Products.Formulator`   an error occurred as in some cases the title of an object was a callable.
> Allow for a callable title on objects in ZODB.

- .toxfiles/coveragerc-py2
- .toxfiles/coveragerc-py3
- .toxfiles/reqs-py2.txt
- .toxfiles/reqs-py3.txt
- CHANGELOG
- perfact/zodbsync/helpers.py
- perfact/zodbsync/tests/test_helpers.py
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
- setup.py
- tox.ini
I think we can finally make this step. We still have systems with `perfact-dbutils-zope2` in the field, but the package has not received any updates since almost one year ago. At least on my current Ubuntu laptop, I have no way of testing if `zodbsync` still works with Python 2. I think with Archlinux it is still possible to execute the tests, but actually I don't think I want to check that.
If we find ourselves in some weird situation where we need to adjust the way `zodbsync` works for the migration of some old system that still wants to keep the decades old code base, the last release that was actually included in `perfact-dbutils-zope2`, namely 22.1.0, should serve as a starting point. I personally doubt that this will be the case.
> Drop support for Python 2

- CHANGELOG
- perfact/zodbsync/tests/environment.py
- perfact/zodbsync/tests/test_sync.py
For systems that have init.defaultBranch set globally
> Explicitly name initial branch in tests

- README.md
Mention nasty version struggle in Caveats chapter. There are even more traps behind the initial error shown, so people should know and just take the right steps.
> T252577: Tell about older tox versions no longer working

- CHANGELOG
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
This PR fixes an issue where zodbsync was overwriting the contents of a source-file in a frozen layer. 
The test-case is as follows:
1. We record an object into the custom layer
2. The filesystem objects are moved to the frozen layer manually
3. The content in the Data.FS is modified, in this case we edith both the meta aswell as the content data
4. A record is executed. 
The expected behaviour would be that the changed meta and source files are both written into the custom-layer. The actual behaviour is that the `__meta__`-File is correctly written into the custom-layer but the `__source__`-File is modified in the frozen layer below!
The issue was that the path which was generated for the source-file was based on the layer-path while the path for the meta-file was generated based upon …
> Sync writes __source__ falsely into frozen layers

- CHANGELOG
- perfact/zodbsync/subcommand.py
Mostly a cosmetic issue, I was wondering about the output of
```
ZODBSync INFO Using user perfact
ZODBSync INFO Uploading .gitignore/
ZODBSync INFO Uploading README.md/
ZODBSync INFO Uploading debian/changelog/
ZODBSync INFO Uploading debian/control/
ZODBSync INFO Uploading debian/rules/
ZODBSync INFO Uploading debian/source/format/
ZODBSync INFO Uploading extract-checksums/
```
during a `zodbsync reset` on a system where a debianized layer package is still checked out.
> Only try to playback paths below __root__

- .github/workflows/check.yml
- CHANGELOG
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
Ran into the problem today that changes in a custom layer with `__deleted__` markers were passed to the playback hook, which created entries in `dbmodreg` with three components (`yyyy-mm-dd_000_suffix/000/__deleted__`), which failed when the dbmods were to be applied because it only works with two parts when splitting with `/`.
> Fix path normalization for __deleted__ and __frozen__ markers

- perfact/zodbsync/zodbsync.py
On a layers system this logger line is always displayed for missing files. This PR moves the log line right next to the deletion to ensure the output is more concise with what is deleted.
> T282763: Make zodbsync record output more specific

- perfact/zodbsync/commands/watch.py
- perfact/zodbsync/tests/test_sync.py
- perfact/zodbsync/zodbsync.py
Well, does what is says on the tin (atleast proof of concept wise)! Basically I had the idea that the Data.FS should just know from which layer an object was uploaded so we can make use of this information inside of the application (for example the ZMI). For this we just store the layer-ident in the `zodbsync_layer` property of an object (not the PropertySheet functionality, but just actual python properties), which are just as happily written into the Data.FS!
Whats currently missing is the "update" of this property in case the file is changed in Zope and therefor changes it`s source-layer! But I wanted to wait to implement something for this until I got feedback on whether this is actually something we would like to pursue further. 
For testing purposes I actually patched the ZMI to …
> Write layer-source of object into Data.FS
